### ISSUE TITLE
No submodule mapping found

### ISSUE THREAD

**Issue by chap** [particle-iot/ios-app-example-carthage#1]
First time using carthage, so I'm probably doing something stupid, but following the readme instructions fails here:

```
$ git clone git@github.com:spark/ios-app-example-carthage.git
Cloning into 'ios-app-example-carthage'...
Checking connectivity... done.
$ cd ios-app-example-carthage/
$ . bin/setup 
*** Fetching spark-setup-ios
*** Fetching spark-sdk-ios
*** Fetching AFNetworking
*** Checking out AFNetworking at "3.1.0"
*** Checking out spark-sdk-ios at "0.4.1"
*** Checking out spark-setup-ios at "0.4.0"
A shell task (/usr/bin/env git submodule --quiet init -- Carthage/Checkouts/AFNetworking) failed with exit code 1:
No submodule mapping found in .gitmodules for path 'Carthage/Checkouts/AFNetworking'
```

**Comment by peewee** [comment]
hullo old Chap

Bash into top project folder. 
Paste 
    'carthage update --platform iOS --use-submodules --no-use-binaries'
after Fetching & Checking out, fails ...

warning: failed to load toolchain 'com.apple.dt.toolchain.iOS9_3': Could not find toolchain: com.apple.dt.toolchain.iOS9_3warning: failed to load toolchain 'com.apple.dt.toolchain.iOS9_3': Could not find toolchain: com.apple.dt.toolchain.iOS9_3*** Building scheme "ParticleSDK" in spark-sdk.xcworkspace

here I,m stuck with a new blank project
however "ios-app-example-carthage" will work
p

**Comment by RaimundasSakalauskas** [comment]
Closing this as outdated. I have added submodule mappings, but in case you have the same issue in the future it is easy to resolve by "git submodule deinit --all" and running "bin/setup" again.
